#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Apr 30 12:09:49 CST 2026
maven-metadata-central.xml/@www-proxy.us.oracle.com\:80>22005f03160331a3cd04fe97568775f2b8bbe0b6@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1777572589235
maven-metadata-central.xml.error=Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/to central (https\://repo.maven.apache.org/maven2)\: www-proxy.us.oracle.com\: nodename nor servname provided, or not known
