spring:
  application:
    name: juro
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/juro}
    username: ${JDBC_DATABASE_USERNAME:juro}
    password: ${JDBC_DATABASE_PASSWORD:juro}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
